config/routes.rb
Rails.application.routes.draw do
  mount StripeEvent::Engine => '/stripe'

  resources :organizations

  resources :menus
  resources :setup_organization
  resources :restaurants do
    collection do
      get 'export_menus'
    end
  end

  devise_for :users#, :controllers => { :registrations => "registrations" }

    authenticated do
      get '/' => 'dashboard#show', :constraints => Subdomain, :as => 'dashboard'
    end

   
  get 'home/index', :as => 'home'
  
  root 'home#index'

  

end

app/models/menu.rb
require 'csv'

class Menu < ActiveRecord::Base
  belongs_to :restaurant
  has_many :items, dependent: :destroy
  resourcify
  
  accepts_nested_attributes_for :items
  
  
  def self.export_to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |menu|
        csv << menu.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/menus_controller.rb
require 'csv'

class MenusController < ApplicationController
 before_action :set_menu, only: [:show, :edit, :update, :destroy]

  def index
    @menus = Menu.all
    
    respond_to do |format|
      format.html
      format.csv { render text: @menus.export_to_csv }
    end
  end

  def show
  end

  def new
    @menu = Menu.new
  end

  def edit
  end

  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render action: 'show', status: :created, location: @menu }
      else
        format.html { render action: 'new' }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :no_content }
    end
  end

  private

    def set_menu
      @menu = Menu.find(params[:id])
    end

    def menu_params
      params.require(:menu).permit(:title, :description, :restaurant_id,
           :items_attributes => [:id, :name, :description, :price, :_destroy]
                                   )
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.haml
= nested_form_for(@menu) do |f|
  - if @menu.errors.any?
    #error_explanation
      %h2
        = pluralize(@menu.errors.count, "error")
        prohibited this menu from being saved:
      %ul
        - @menu.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :title
    %br/
    = f.text_field :title, :class=>"form-control", :placeholder => "Title"
  .form-group
    = f.label :description
    %br/
    = f.text_area :description, :class=>"form-control", :placeholder => "Description"
  %h3 Items
  = f.fields_for :items do |i|
    .form-group
      = i.label :name
      %br/
      = i.text_field :name, :class=>"form-control", :placeholder => "Name"
    .form-group
      = i.label :price
      %br/
      = i.text_field :price, :class=>"form-control", :placeholder => "Price"
    .form-group
      = i.label :description
      %br/
      = i.text_area :description, :class=>"form-control", :placeholder => "Description"
    = i.link_to_remove "Remove this item", :class=>"btn btn-default"
  %p= f.link_to_add "Add an Item", :items, :class=>"btn btn-default"
  = f.hidden_field :restaurant_id, :value => params[:restaurant_id]
  .actions
    = f.submit 'Create Menu', :class=>"btn btn-default"

app/views/menus/edit.html.haml
%h1 Editing menu

= render 'form'

= link_to 'Show', @menu
\|
= link_to 'Back', menus_path

app/views/menus/index.html.haml
%tbody
  - @menus.each do |menu|
    %tr
      %td
        %h2= menu.title
      %td= menu.description
      %br/
      %td= link_to 'Show', menu, :class=>"btn btn-primary"
      %td= link_to "Export to CSV", menus_path(format: "csv"), :class=>"btn btn-warning"
      - if current_user.has_role? "owner"
        %td= link_to 'Edit', edit_menu_path(menu)
        %td= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' }

%br/
%br/
%br/
= link_to 'New Menu', new_menu_path, :class=>"btn btn-success"

app/views/menus/new.html.haml
%h3 Add a Menu
= render 'form'
%br/
= link_to 'Cancel', menus_path, :class=>"btn btn-default"

app/views/menus/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @menu.title
%p
  %br/
  %strong Description:
  = @menu.description
%br/ 
  
- @menu.items.each do |i|
  %strong= i.name
  %br/
  = i.description
  %br/
  %strong= i.price 
  %br/
= link_to 'Edit', edit_menu_path(@menu)
|
\#{link_to 'Back', menus_path}