config/routes.rb
Rails.application.routes.draw do
  mount StripeEvent::Engine => '/stripe'

  resources :organizations

  resources :menus
  resources :setup_organization
  resources :restaurants do
    collection do
      get 'export_menus'
    end
  end

  devise_for :users#, :controllers => { :registrations => "registrations" }

    authenticated do
      get '/' => 'dashboard#show', :constraints => Subdomain, :as => 'dashboard'
    end

   
  get 'home/index', :as => 'home'
  
  root 'home#index'

  

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  include Concerns::Access

  # extend FriendlyId
  # friendly_id :name, use: :slugged
  
  has_many :menus, dependent: :destroy
  belongs_to :organization
  resourcify
  
  validates :name, presence: true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  include Concerns::Access

  def index
    @organization = current_user.organizations
    if params[:id].present?
      @restaurants = @tenant.restaurants.find(params[:id])
    else
      @restaurants = Restaurant.all
    end
  end

  def show
    @menus = Menu.where(:restaurant_id => @restaurant.id)
  end
  require 'csv'
  def export_menus
    @menus = Menu.where(:restaurant_id => params[:restaurant_id])
    respond_to do |format|
      format.html
      format.csv { render text: @menus.export_to_csv }
    end
  end

  def new
    @restaurant = Restaurant.new
    @organization = current_user.organizations
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.organization_id = current_user.organizations

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render action: 'show', status: :created, location: @restaurant }
      else
        format.html { render action: 'new' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end

  private

    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(:name, :description, :organization_id, :users_attributes => [:id, :name, :email, :password, :password_confirmation, :remember_me]
)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
 def resource_name
  :user
 end

 def resource
  @resource ||= User.new
 end

 def devise_mapping
  @devise_mapping ||= Devise.mappings[:user]
 end
 
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource_name)

    html = <<-HTML
<div id="error_explanation">
<h2>#{sentence}</h2>
<ul>#{messages}</ul>
</div>
HTML

    html.html_safe
  end
end

app/views/restaurants/_form.html.haml
= form_for(@restaurant) do |f|
  = render 'form_errors'
  .form-group
    = f.label :name
    %br/
    = f.text_field :name, :class=>"form-control", :placeholder => "Restaurant Name"
  .form-group
    = f.label :description
    %br/
    = f.text_area :description , :class=>"form-control", :placeholder => "Description"
  / <haml_loud> f.hidden_field :organization_id, :value => @organization</haml_loud>
  .actions
    = f.submit :class=>"btn btn-default"
    = link_to 'Cancel', restaurants_path, :class=>"btn btn-default"

app/views/restaurants/_form_errors.html.haml
- if @restaurant.errors.any?
  #error_explanation
    %h2
      = pluralize(@restaurant.errors.count, "error")
      prohibited this restaurant from being saved:
    %ul
      - @restaurant.errors.full_messages.each do |msg|
        %li= msg

app/views/restaurants/edit.html.haml
%h1 Editing restaurant

= render 'form'

= link_to 'Show', @restaurant
\|
= link_to 'Back', restaurants_path

app/views/restaurants/index.html.haml
%h2
  / = @organization.name
  %tbody
    - @restaurants.each do |restaurant|
      %tr
        %td= restaurant.name
        %br/
        %td= restaurant.description
        %br/
        %td= link_to 'Show', restaurant, :class=>"btn btn-default"
        %br/
        - if current_user.has_role? "owner"
          %td= link_to 'Edit', edit_restaurant_path(restaurant), :class=>"btn btn-default"
          %td= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-default"
  %br/
  %br/
  = link_to 'Add A Restaurant', new_restaurant_path, :class=>"btn btn-default"

app/views/restaurants/new.html.haml
%h1 New restaurant

= render 'form'

= link_to 'Back', restaurants_path

app/views/restaurants/show.html.haml
%p#notice= notice

%p
  %strong Name:
  = @restaurant.name

%p
  %strong Description:
  = @restaurant.description

%h3 Menus
- @menus.each do |m|

  = link_to m.title, menu_path(m)

  = link_to "Export to CSV", export_menus_restaurants_path(format: "csv", :restaurant_id => @restaurant.id), :class=>"btn btn-default"

= link_to "Add a Menu", new_menu_path(:restaurant_id => @restaurant.id), :class=>"btn btn-default"

= link_to 'Edit', edit_restaurant_path(@restaurant), :class=>"btn btn-default"

= link_to 'Back', restaurants_path, :class=>"btn btn-default"