config/routes.rb
Rails.application.routes.draw do
  mount StripeEvent::Engine => '/stripe'

  resources :organizations

  resources :menus
  resources :setup_organization
  resources :restaurants do
    collection do
      get 'export_menus'
    end
  end

  devise_for :users#, :controllers => { :registrations => "registrations" }

    authenticated do
      get '/' => 'dashboard#show', :constraints => Subdomain, :as => 'dashboard'
    end

   
  get 'home/index', :as => 'home'
  
  root 'home#index'

  

end

app/models/organization.rb
class Organization < ActiveRecord::Base
#   include Concerns::Access
  has_one :plan
  resourcify
  
  has_and_belongs_to_many :users


  # organizations_users
  validates :name, presence: true

  def self.free_trial
    date_today = Date.today
    if TimeDifference(self.created_at, date_today).in_months == 1
      
       errors.add :base, "Unable to update your subscription. #{e.message}."
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:new] 

  def index
    @organizations = Organization.where(:name => request.subdomain).first
  end

  def show
  end

  def new
    @organization = Organization.new
    @plan = Plan.where(:id=> params[:plan_id]).pluck(:name)
  end

  def edit
     @organization.users.each do |u|
      if u.plan_id.present?
  @plan = Plan.where(:id=> u.plan_id).pluck(:name)
      end
     end
  end

  def create
    @user = current_user
    @organization = Organization.new(organization_params)
    @organization.users << @user

     
    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render action: 'show', status: :created, location: @organization }
      else
        format.html { render action: 'new' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to dashboard_path, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end

  private

    def set_organization
      @organization = Organization.find(params[:id])
    end

    def organization_params
      params.require(:organization).permit(:name, :description, :plan_id, {:user_ids => []})
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper

 def resource_name
  :user
 end

 def resource
  @resource ||= User.new
 end

 def devise_mapping
  @devise_mapping ||= Devise.mappings[:user]
 end
end

app/views/organizations/_form.html.haml
= form_for(@organization) do |f|
  - if @organization.errors.any?
    #error_explanation
      %h2
        = pluralize(@organization.errors.count, "error")
        prohibited this organization from being saved:
      %ul
        - @organization.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label 'Organization Name'
    = f.text_field :name, :class=>"form-control", :placeholder => "Organization Name"
  .form-group
    = f.label :description
    = f.text_area :description, :class=>"form-control", :rows=>"3", :placeholder => "Description"
  %h3
    Plan Selected: #{@plan.first}
  = f.hidden_field :plan_id, :value => params[:plan_id]
  = f.submit "Update", :class=>"btn btn-default"

app/views/organizations/_wizard.html.haml
= form_for(@organization , :url => wizard_path, :method => :put) do |f|
  - if @organization.errors.any?
    #error_explanation
      %h2
        = pluralize(@organization.errors.count, "error")
        prohibited this organization from being saved:
      %ul
        - @organization.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label 'Organization Name'
    = f.text_field :name, :class=>"form-control", :placeholder => "Organization Name"
  .form-group
    = f.label :description
    = f.text_area :description, :class=>"form-control", :rows=>"3", :placeholder => "Description"
  = f.submit 'Create', :class=>"btn btn-default"

app/views/organizations/edit.html.haml
%h1 Editing organization
= render 'form'
= link_to 'Show', @organization
|
=link_to 'Back', organizations_path}

app/views/organizations/index.html.haml
%h1 Listing organizations
%table
  %thead
    %tr
      %th Name
      %br/
      %th Description
      %br/
      %th Owner
      %br/
      %th
      %th
      %th
  %tbody
    - @organizations.each do |organization|
      %tr
        %td= organization.name
        %br/
        %td= organization.description
        %br/
        %td= link_to 'Show', organization
        %td= link_to 'Edit', edit_organization_path(organization)
        %td= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Organization', new_organization_path

app/views/organizations/new.html.haml
%h2 Setup Your Organization
= render 'form'

app/views/organizations/show.html.haml
%p#notice= notice
%p
%br/
  %strong Name:
  = @organization.name
%p
%br/
  %strong Description:
  = @organization.description

= link_to 'Edit', edit_organization_path(@organization)
|
= link_to 'Back', organizations_path